import { Card } from "./card";

export const cards = {
  1: new Card("the-blind-man", "1-4-7"),
  2: new Card("the-belltower", "discard-lower"),
  3: new Card("the-beast", "twice"),
  4: new Card("the-deep", "higher-than"),
  5: new Card("dawn", "higher-than"),
  6: new Card("the-chalice", "1-4-7"),
  7: new Card("the-judge", "3-4-5"),
  8: new Card("the-huntress", "twice"),
  9: new Card("the-engine", "5-6-7"),
  10: new Card("the-lord", "5-6-7"),
  11: new Card("leviathan", "discard-lower"),
  12: new Card("the-key", "old"),
  13: new Card("the-noble", "3-4-5"),
  15: new Card("the-mirror", "twice"),
  16: new Card("midnight", "higher-than"),
  17: new Card("the-servant", "1-2-3"),
  18: new Card("the-rider", "cycle"),
  19: new Card("the-prophet", "cycle"),
  20: new Card("asunder", "same"),
  21: new Card("the-stranger", "1-2-3"),
  22: new Card("the-shore", "discard-lower"),
  23: new Card("fortune", "plus-1"),
  24: new Card("the-feast", "relocate"),
  25: new Card("the-captain", "1-4-7"),
  26: new Card("the-lantern", "relocate"),
  27: new Card("iron", "plus-1"),
  28: new Card("the-ghost", "plus-1"),
  29: new Card("the-wish", "old"),
  30: new Card("the-passage", "same"),
  31: new Card("the-pallbearers", "within-2"),
  32: new Card("the-thief", "help"),
  33: new Card("the-north-wind", "slow"),
  34: new Card("the-musicians", "exile"),
  35: new Card("the-fall", "amplify"),
  36: new Card("the-ash", "help"),
};
