import { Card } from "./card";

export const cards = {
  1: new Card("asunder"),
  2: new Card("the-engine"),
  3: new Card("the-noble"),
  4: new Card("dawn"),
  5: new Card("the-fall"),
  6: new Card("the-north-wind"),
  7: new Card("fortune"),
  8: new Card("the-feast"),
  9: new Card("the-pallbearers"),
  10: new Card("iron"),
  11: new Card("the-ghost"),
  12: new Card("the-passage"),
  13: new Card("leviathan"),
  15: new Card("the-prophet"),
  16: new Card("midnight"),
  17: new Card("the-huntress"),
  18: new Card("the-rider"),
  19: new Card("the-ash"),
  20: new Card("the-imago"),
  21: new Card("the-servant"),
  22: new Card("the-beast"),
  23: new Card("the-judge"),
  24: new Card("the-shore"),
  25: new Card("the-belltower"),
  26: new Card("the-key"),
  27: new Card("the-stranger"),
  28: new Card("the-blind-man"),
  29: new Card("the-lantern"),
  30: new Card("the-wish"),
  31: new Card("the-captain"),
  32: new Card("the-lord"),
  33: new Card("thief"),
  34: new Card("the-chalice"),
  35: new Card("the-mirror"),
  36: new Card("the-deep"),
  37: new Card("the-musicians"),
};
